language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-28
  - extra-android-support
  - extra-android-m2repository
licenses:
- 'android-sdk-license-.+'
script:
- ./gradlew assemblePaidRelease
before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew
before_deploy:
- ls app/build/outputs/apk/paid
- cp app/build/outputs/apk/paid/*.apk bridge-$TRAVIS_BUILD_NUMBER.apk
deploy:
- provider: script
  skip_cleanup: true
  script: sh scripts/deploy.sh
  on:
    branch: master
branches:
  only:
  - master
after_failure: cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml
